create schema if not exists client;

create table if not exists client.Users
(
    id       bigint primary key generated by default as identity,
    username varchar(30) not null,
    password varchar(50) not null
)