create schema if not exists orders;

create table if not exists orders.Orders
(
    id          bigint primary key generated by default as identity,
    customer_id bigint      not null,
    total       double precision                    not null,
    order_date  timestamp                           not null default current_timestamp,
    updated_at  timestamp                           not null default current_timestamp,
    status      varchar(20) not null default 'PENDING',
    products    json        not null
)