create table if not exists catalog.Products
(
    id          bigint primary key generated by default as identity,
    name        varchar(200) not null unique,
    price       double precision check ( price > 0.0 ),
    category_id bigint references catalog.Categories (id)
)